on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox

      - name: Run lint
        run: |
           tox -e lint

  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.12'
    name: py${{ matrix.python-version }}_test
    runs-on: ubuntu-latest
    services:
      tidb:
        image: wangdi4zm/tind:v7.5.3-vector-index
        ports:
          - 4000:4000
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh-actions
          sudo apt-get update
          sudo apt-get install -y libmemcached-dev zlib1g-dev

      - name: Run tests
        run: tox
